# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns all \code{A} records associated with a hostname
#'
#' Takes in a hostname and returns all IP DNS entries for it. Not vectorized.
#'
#' @param hostname character string of host to lookup
#' @return vector IP addresses
#' @examples
#' \dontrun{
#' # forward
#' gethostbyname("dds.ec")
#' ## [1] "162.243.111.4"
#'
#' # multiple return values
#' gethostbyname("google.com")
#' ##  [1] "2607:f8b0:4006:806::100e" "74.125.226.14"
#' ##  [3] "74.125.226.8"             "74.125.226.3"
#' ##  [5] "74.125.226.6"             "74.125.226.4"
#' ##  [7] "74.125.226.9"             "74.125.226.0"
#' ##  [9] "74.125.226.2"             "74.125.226.1"
#' ## [11] "74.125.226.5"             "74.125.226.7"
#' }
gethostbyname <- function(hostname) {
    .Call('iptools_gethostbyname', PACKAGE = 'iptools', hostname)
}

#' Returns all \code{PTR} records associated with an IPv4 address
#'
#' Takes in an IPv4 address and returns all IP reverse DNS entries for it. Not vectorized.
#'
#' @param ipv4 character string (dotted-decimal) IPv4 address
#' @return vector of hostnames (will usually be just a single host)
#' @examples
#' \dontrun{
#' # reverse
#' gethostbyaddr(gethostbyname("dds.ec"))
#' ## [1] "162.243.111.4"
#' }
gethostbyaddr <- function(ipv4) {
    .Call('iptools_gethostbyaddr', PACKAGE = 'iptools', ipv4)
}

#' Character (dotted-decimal) IPv4 Address Conversion to long integer
#'
#' Convert IP addresses in character (dotted-decimal) notation to long integers
#'
#' @param ip input character vector of IPv4 addresses (dotted-decimal)
#' @return vector of equivalent long integer IP addresses
#' @examples
#' \dontrun{
#' ip2long("24.0.5.11")
#' ip2long(c("24.0.5.11", "211.3.77.96"))
#' }
ip2long <- function(ip) {
    .Call('iptools_ip2long', PACKAGE = 'iptools', ip)
}

#' Intger IPv4 Address Conversion to Character
#'
#' Converts IP addresses in long integer format to character (dotted-decimal) notation
#'
#' @param ip input numeric (long integer) vector
#' @return vector of equivalent character (dotted-decimal) IP addresses
#' @examples
#' \dontrun{
#' long2ip(402654475)
#' long2ip(c(402654475, 3540208992))
#' }
long2ip <- function(ip) {
    .Call('iptools_long2ip', PACKAGE = 'iptools', ip)
}

#' Initializes the maxmind library and opens the \code{GeoLiteCity.dat} file
#'
#' This function must be called before performing a lookup with \code{geoip()}.
#' The default full path spec defaults to \code{/usr/local/share/GeoIP/GeoLiteCity.dat}
#' and can be overriden by changing the value of the \code{datafile} parameter.
#'
#' NOTE: You must manually retrieve the \code{GeoLiteCity.dat.gz} file from maxmind
#' via \url{http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz} and
#' unzip it to the location you will be specifying in \code{datafile}.
#'
#' Any errors reading the file will result in a console message.
#'
#' @param datafile full path (including filename) to the \code{GeoLiteCity.dat} file
#' @examples
#' \dontrun{
#' geofile()
#' }
geofile <- function(datafile = "/usr/local/share/GeoIP/GeoLiteCity.dat") {
    invisible(.Call('iptools_geofile', PACKAGE = 'iptools', datafile))
}

#' Return a data frame of geolcation values for IPv4 address
#'
#' Uses the maxmind \code{GeoIPCity.dat} binary file to perform a geolocation for
#' a given IPv4 address and returns a data frame of geolocation records.
#' You must call \code{geofile()} before calling \code{geoip()}
#'
#' Values returned in the data frame:
#' \itemize{
#'   \item \code{ip}. original IP address (chr)
#'   \item \code{country.code}. ISO2 country code (chr)
#'   \item \code{country.code3}. ISO3 country code (chr)
#'   \item \code{region}. Abbreviated region name (chr)
#'   \item \code{region.name}. Full region name (chr)
#'   \item \code{city}. City name (chr)
#'   \item \code{postal.code}. Postal code (chr)
#'   \item \code{latitude}. Latitude (numeric)
#'   \item \code{lontigude}. Longitude (numeric)
#'   \item \code{time.zone}. Time zone (chr)
#'   \item \code{metro.code}. Metro code (int)
#'   \item \code{area.code}. Area code (int)
#' }
#'
#' @param ip character vector of IPv4 addresses to lookup
#' @param showMessages show/hide console messages (bool) default: do not show messages
#' @return data frame of geolocation information for the IP addresses
#' @note  vectorized
#' @examples
#' \dontrun{
#' geofile()
#' geoip(c("24.24.24.24", "42.42.42.42", "8.8.8.8"))
#' ##            ip country.code country.code3       country.name region region.name      city
#' ## 1 24.24.24.24           US           USA      United States     NY    New York Deer Park
#' ## 2 42.42.42.42           KR           KOR Korea, Republic of     NA          NA        NA
#' ## 3     8.8.8.8           US           USA      United States     NA          NA        NA
#' ##   postal.code latitude longitude        time.zone metro.code area.code
#' ## 1       11729  40.7627  -73.3227 America/New_York        501       631
#' ## 2          NA  37.5700  126.9800       Asia/Seoul          0         0
#' ## 3          NA  38.0000  -97.0000               NA          0         0
#' }
geoip <- function(ip, showMessages = FALSE) {
    .Call('iptools_geoip', PACKAGE = 'iptools', ip, showMessages)
}

#' Called when finished performing geolocation operations
#'
#' This frees the memory associated with the geolocation file.
#'
#' @examples
#' \dontrun{
#' geoCleanup()
#' }
geoCleanup <- function() {
    invisible(.Call('iptools_geoCleanup', PACKAGE = 'iptools'))
}

